require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

install! 'cocoapods', :deterministic_uuids => false

platform :ios, '11.0'

def pods()
  # // Get config
  config = use_native_modules!

  fabric_enabled = ENV['USE_FABRIC']
  use_codegen_discovery= ENV['USE_CODEGEN_DISCOVERY']

  use_react_native!(
    path: config[:reactNativePath],
    fabric_enabled: fabric_enabled,
    hermes_enabled: true,
    app_path: "#{Dir.pwd}/..",
  )

  #   use_react_native_codegen_discovery!({
  #     react_native_path: config[:reactNativePath],
  #     # Modify here if your app root path isn't the same as this one.
  #      app_path: "#{Dir.pwd}/..",
  #      fabric_enabled: true
  # })
end

target 'ReactNativeTurbomoduleFabricRendererBoilerpate' do
  pods()
  config = use_native_modules!

  target 'ReactNativeTurbomoduleFabricRendererBoilerpateTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
